# Generated by Django 4.1 on 2022-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(default=1, verbose_name='year'),
            preserve_default=False,
        ),
    ]
